apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: orbitstream
    user: postgres
    editable: false
    isDefault: true
    jsonData:
      postgresVersion: 1600
      timescaledb: true
      database: orbitstream
      sslmode: disable
    secureJsonData:
      password: postgres
    version: 1
